### ISSUE TITLE
Broken Video in README.

### ISSUE THREAD

**Issue by SylvanFranklin** [avencera/easywind#4]
Pretty much what the title says, I can't see the contents of this video. It shows up with the following error. 

<img width="958" alt="Screenshot 2024-11-05 at 2 51 00 PM" src="https://github.com/user-attachments/assets/4869714e-9668-4e0b-8ae8-dff7d28632cf">

**Comment by praveenperera** [comment]
sounds like a browser issue for you, works fine on safari and chrome for me

**Comment by SylvanFranklin** [comment]
Okay thanks!

**Comment by praveenperera** [comment]
can you try a different browser? are you on window?

**Comment by SylvanFranklin** [comment]
No I am on MacOS. It just seems to be a Firefox based rendering issue which is not that big of a deal. It works for me in chrome, safari, edge, and arc. I'm running the latest FireFox and the video fails to load with and without extensions enabled. I think that you can safely ignore this and just wait for FireFox to fix it on their end. Thanks for the patience.
